import { ReactNode } from "react";
import Link from "next/link";

function BrandMark() { return <span className="grid h-9 w-9 place-items-center rounded-xl bg-gradient-to-br from-[#4f7cff] via-[#6d5ef7] to-[#8b5cf6] text-white shadow-[0_0_24px_rgba(79,124,255,.38)]"><svg aria-hidden="true" viewBox="0 0 24 24" className="h-5 w-5" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="m12 2 1.7 6.3L20 10l-6.3 1.7L12 18l-1.7-6.3L4 10l6.3-1.7L12 2Z" /></svg></span>; }
export function AuthCard({ title, subtitle, children, footer }: { title: string; subtitle?: string; children: ReactNode; footer?: ReactNode }) {
  return <main className="relative grid min-h-dvh overflow-hidden bg-[#07080f] text-[#f5f6fa] lg:grid-cols-[55%_45%]"><section className="order-2 relative flex flex-col justify-center px-6 py-10 sm:px-12 lg:px-16"><div className="pointer-events-none absolute -left-24 top-1/4 h-72 w-72 rounded-full bg-[#4f7cff]/15 blur-3xl" /><div className="relative mx-auto w-full max-w-md"><Link href="/" className="mb-10 flex w-fit items-center gap-2.5 text-lg font-semibold tracking-tight"><BrandMark />ClearFrame</Link><div className="rounded-3xl border border-white/10 bg-[#0c0e1a]/85 p-6 shadow-[0_24px_80px_rgba(0,0,0,.3)] backdrop-blur-xl sm:p-8"><h1 className="text-2xl font-semibold tracking-tight">{title}</h1>{subtitle && <p className="mt-2 text-sm leading-6 text-white/55">{subtitle}</p>}<div className="mt-7">{children}</div></div>{footer && <div className="mt-5 text-center text-sm text-white/50">{footer}</div>}</div></section><section className="order-1 relative hidden overflow-hidden border-l border-white/[.06] lg:block"><div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top_right,rgba(79,124,255,.3),transparent_55%),radial-gradient(ellipse_at_bottom_left,rgba(109,94,247,.22),transparent_50%)]" /><div className="absolute inset-10 overflow-hidden rounded-[2rem] border border-white/10 bg-gradient-to-br from-[#171d38] via-[#0e1322] to-[#211741] shadow-[0_30px_100px_rgba(0,0,0,.4)]"><img src="/demo/owned-after.png" alt="Clean result on owned sample footage" className="absolute inset-0 h-full w-full object-cover opacity-55" /><div className="absolute inset-0 bg-gradient-to-t from-[#07080f] via-[#07080f]/20 to-transparent" /><div className="absolute bottom-10 left-10 right-10"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#b7c7ff]">Authorized video cleanup</p><h2 className="mt-4 max-w-xl text-4xl font-semibold leading-tight tracking-[-.04em] xl:text-5xl">Refine the footage <span className="bg-gradient-to-r from-[#4f7cff] to-[#22d3ee] bg-clip-text text-transparent">that&apos;s yours.</span></h2><p className="mt-4 max-w-lg leading-7 text-white/60">AI-assisted detection, frame-accurate control, and a reviewable workflow for authorized edits only.</p><div className="mt-6 flex flex-wrap gap-2 text-xs font-medium text-white/70">{["Preserves original audio", "Frame-accurate tracking", "No DRM removal"].map((t) => <span key={t} className="rounded-full border border-white/10 bg-white/5 px-3 py-2">{t}</span>)}</div></div></div></section></main>;
}
export function FieldError({ msg }: { msg?: string }) { return msg ? <p className="mt-1.5 text-sm text-rose-300" role="alert">{msg}</p> : null; }
export function AuthError({ msg }: { msg?: string | null }) { return msg ? <div role="alert" className="mb-4 flex items-start gap-2 rounded-xl border border-rose-500/30 bg-rose-500/10 px-3.5 py-2.5 text-sm text-rose-200"><svg aria-hidden="true" viewBox="0 0 24 24" className="mt-0.5 h-4 w-4 shrink-0" fill="none" stroke="currentColor" strokeWidth="1.8"><circle cx="12" cy="12" r="9" /><path d="M12 8v5M12 16h.01" strokeLinecap="round" /></svg><span>{msg}</span></div> : null; }
export function AuthDivider({ label = "OR" }: { label?: string }) { return <div className="my-5 flex items-center gap-3 text-xs font-medium uppercase tracking-wider text-white/35"><span className="h-px flex-1 bg-white/10" />{label}<span className="h-px flex-1 bg-white/10" /></div>; }
export function NamedLink({ href, children }: { href: string; children: ReactNode }) { return <Link href={href} className="font-medium text-[#9eb4ff] transition hover:text-white hover:underline">{children}</Link>; }
export function friendlyAuthError(err: any, fallback: string) { const status = err?.response?.status; if (err?.code === "EMAIL_NOT_VERIFIED") return "Please verify your email before logging in."; if (err?.code === "ACCOUNT_DELETED") return "This account has been deleted and can no longer be accessed. Contact support if you believe this was a mistake."; if (err?.code === "INVALID_CREDENTIALS" || status === 401) return "Incorrect email or password."; if (status === 429) return "Too many attempts. Please wait a moment."; if (status && status >= 500) return "Something went wrong on our end. Please try again."; return fallback; }

