import Link from "next/link";
import { Check, Mail, Sparkles } from "lucide-react";

import { footerColumns, type FooterLink } from "./footerConfig";

function FooterLinkItem({ link }: { link: FooterLink }) {
  const className = "inline-flex min-h-11 items-center text-sm text-white/60 transition hover:text-white hover:underline hover:underline-offset-4 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300";
  if (link.href.startsWith("mailto:")) return <a href={link.href} className={className}>{link.label}</a>;
  return <Link href={link.href} className={className}>{link.label}</Link>;
}

export default function Footer() {
  return <footer id="resources" className="scroll-mt-24 border-t border-white/10 bg-[#07080f] text-white"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className="grid gap-12 py-16 sm:grid-cols-2 lg:grid-cols-[1.45fr_repeat(4,1fr)]"><div className="sm:col-span-2 lg:col-span-1"><Link href="/" className="inline-flex items-center gap-2.5 text-lg font-semibold"><span className="grid h-9 w-9 place-items-center rounded-xl bg-gradient-to-br from-[#4f7cff] via-[#6d5ef7] to-[#8b5cf6]"><Sparkles size={18} /></span>ClearFrame</Link><p className="mt-4 max-w-xs text-sm leading-6 text-white/55">AI-assisted video cleanup for footage you own or are licensed to edit.</p><a href="mailto:support@clearframe.app" className="mt-5 inline-flex min-h-11 items-center gap-2 rounded-full border border-white/10 px-4 text-sm text-white/65 transition hover:border-white/25 hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300"><Mail size={15} /> support@clearframe.app</a></div>{footerColumns.map((column) => <nav key={column.title} aria-label={`${column.title} links`}><h2 className="text-xs font-semibold uppercase tracking-[.18em] text-white/40">{column.title}</h2><ul className="mt-4 space-y-1.5">{column.links.map((link) => <li key={link.href}><FooterLinkItem link={link} /></li>)}</ul></nav>)}</div><div className="flex flex-wrap gap-2 border-t border-white/[.07] py-5">{["Authorized use only", "Preview before full render", "No DRM removal", "MP4 · MOV · WebM"].map((badge) => <span key={badge} className="inline-flex items-center gap-1.5 rounded-full border border-white/10 bg-white/[.03] px-3 py-1.5 text-xs text-white/60"><Check size={13} className="text-cyan-100" />{badge}</span>)}</div><div className="flex flex-col gap-3 border-t border-white/[.07] py-5 text-xs text-white/45 sm:flex-row sm:items-center sm:justify-between"><p>© {new Date().getFullYear()} ClearFrame. All rights reserved.</p><div className="flex flex-wrap items-center gap-4"><Link href="/terms" className="inline-flex min-h-11 items-center hover:text-white">Terms</Link><Link href="/privacy" className="inline-flex min-h-11 items-center hover:text-white">Privacy</Link><Link href="/acceptable-use" className="inline-flex min-h-11 items-center hover:text-white">Acceptable Use</Link><Link href="/security" className="inline-flex min-h-11 items-center hover:text-white">Security</Link><Link href="/contact" className="inline-flex min-h-11 items-center hover:text-white">Contact</Link></div></div></div></footer>;
}
