import Link from "next/link";
import {
  ArrowRight,
  Check,
  ChevronDown,
  CircleAlert,
  CircleCheck,
  Clock3,
  FileCheck2,
  FileVideo2,
  Layers3,
  LockKeyhole,
  MoveRight,
  ScanSearch,
  ShieldCheck,
  Sparkles,
  Users,
  Workflow,
  X,
} from "lucide-react";

import type { SeoEntry, SeoPage, SeoSection } from "@/components/seoPages";
import { ProductHeroVisual } from "./ProductVisuals";

function HeroArtwork({ page }: { page: SeoPage }) {
  if (page.kind === "workflow") return <ProductHeroVisual kind="overview" />;
  if (page.kind === "creator") return <div className="overflow-hidden rounded-[1.75rem] border border-white/10 bg-[#10121f] p-3 shadow-[0_28px_90px_rgba(0,0,0,.42)]"><div className="rounded-2xl border border-white/10 bg-[#0c0e1a] p-4"><div className="flex items-center justify-between"><span className="text-xs font-medium text-white/70">Creator projects</span><span className="rounded-full bg-cyan-300/10 px-2 py-1 text-[9px] font-semibold text-cyan-100">3 active</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{[["Archive refresh", "Preview ready", "from-[#223c58] to-[#c77668]"], ["Course update", "Mask review", "from-[#2f3a63] to-[#9e6787]"], ["Travel journal", "Analyzing", "from-[#236371] to-[#d1a265]"], ["Brand reel", "Completed", "from-[#35476d] to-[#6a8e83]"]].map(([title, status, palette], index) => <div key={title} className="overflow-hidden rounded-xl border border-white/10 bg-white/[.025]"><div className={`relative aspect-video bg-gradient-to-br ${palette}`}><span className="absolute bottom-0 right-[18%] h-[62%] w-[26%] rounded-t-[45%] bg-black/25" /><span className="absolute bottom-[14%] left-[12%] h-[8%] w-[48%] rounded-full bg-black/20" />{index === 0 && <span className="absolute right-2 top-2 rounded bg-white/80 px-2 py-1 text-[7px] font-bold text-slate-800">OLD MARK</span>}</div><div className="p-3"><p className="text-xs font-medium text-white">{title}</p><p className="mt-1 text-[10px] text-white/40">{status}</p></div></div>)}</div></div></div>;
  if (page.kind === "editor") return <div className="overflow-hidden rounded-[1.75rem] border border-white/10 bg-[#10121f] p-4 shadow-[0_28px_90px_rgba(0,0,0,.42)]"><div className="grid gap-3 sm:grid-cols-[1fr_160px]"><div className="relative aspect-video overflow-hidden rounded-xl bg-[linear-gradient(145deg,#1a3a50,#764f70_62%,#171827)]"><span className="absolute left-[12%] top-[18%] h-[28%] w-[26%] border-2 border-cyan-300 bg-cyan-300/10" /><span className="absolute bottom-4 left-4 rounded bg-[#07080f]/80 px-2 py-1 text-[9px] text-cyan-100">Mask 01 · selected</span></div><div className="space-y-2">{["Rectangle", "Polygon", "Brush", "Eraser"].map((tool, index) => <span key={tool} className={`flex min-h-11 items-center gap-2 rounded-xl border px-3 text-xs ${index === 1 ? "border-[#4f7cff]/50 bg-[#4f7cff]/15 text-white" : "border-white/10 text-white/45"}`}><Layers3 size={13} />{tool}</span>)}</div></div><div className="mt-4 rounded-xl border border-white/10 bg-[#0c0e1a] p-3"><div className="flex items-center gap-2">{["Footage", "Mask", "Preview", "Review", "Export"].map((step, index) => <div key={step} className="flex flex-1 items-center gap-2"><span className={`h-2 w-2 shrink-0 rounded-full ${index < 3 ? "bg-cyan-300" : "bg-white/15"}`} /><span className="hidden text-[9px] text-white/45 lg:inline">{step}</span>{index < 4 && <span className="h-px flex-1 bg-white/10" />}</div>)}</div></div></div>;
  if (page.kind === "agency") return <div className="rounded-[1.75rem] border border-white/10 bg-[#10121f] p-4 shadow-[0_28px_90px_rgba(0,0,0,.42)]"><div className="flex items-center justify-between"><p className="text-xs font-medium text-white/70">Project organization</p><span className="inline-flex items-center gap-1 text-[9px] text-cyan-100"><Users size={11} /> Single account today</span></div><div className="mt-4 space-y-2">{[["Campaign cut A", "Preview ready", "emerald"], ["Client archive 07", "Mask review", "cyan"], ["Product reel", "Processing", "violet"], ["Licensed clip", "Authorization check", "amber"]].map(([title, status, tone]) => <div key={title} className="grid grid-cols-[1fr_auto] items-center gap-3 rounded-xl border border-white/10 bg-white/[.025] p-3"><span><span className="block text-xs font-medium text-white">{title}</span><span className="mt-1 block text-[10px] text-white/35">Owned or client-approved source</span></span><span className={`rounded-full px-2 py-1 text-[9px] ${tone === "emerald" ? "bg-emerald-300/10 text-emerald-200" : tone === "amber" ? "bg-amber-300/10 text-amber-100" : "bg-cyan-300/10 text-cyan-100"}`}>{status}</span></div>)}</div><div className="mt-3 rounded-xl border border-dashed border-white/15 p-3 text-center text-[10px] text-white/35">Team roles and shared billing · planned, not active</div></div>;
  if (page.kind === "compliance") return <div className="grid gap-3 sm:grid-cols-2"><div className="rounded-[1.5rem] border border-emerald-300/20 bg-emerald-300/[.055] p-5"><CircleCheck className="text-emerald-200" /><p className="mt-4 text-xs font-semibold uppercase tracking-[.16em] text-emerald-200">Allowed</p><p className="mt-2 text-lg font-semibold">Your own logo</p><p className="mt-2 text-sm leading-6 text-white/45">A self-owned mark on footage you created.</p></div><div className="rounded-[1.5rem] border border-rose-300/20 bg-rose-300/[.045] p-5"><CircleAlert className="text-rose-200" /><p className="mt-4 text-xs font-semibold uppercase tracking-[.16em] text-rose-200">Not allowed</p><p className="mt-2 text-lg font-semibold">Stock preview mark</p><p className="mt-2 text-sm leading-6 text-white/45">A third-party ownership notice or access control.</p></div><div className="sm:col-span-2 rounded-[1.5rem] border border-white/10 bg-[#10121f] p-5"><div className="grid grid-cols-3 gap-3 text-center">{[["Confirm", ShieldCheck], ["Record", FileCheck2], ["Retain", LockKeyhole]].map(([label, Icon]) => { const C = Icon as typeof ShieldCheck; return <div key={label as string}><C className="mx-auto text-cyan-100" size={18} /><p className="mt-2 text-[10px] text-white/45">{label as string}</p></div>; })}</div></div></div>;
  if (page.kind === "formats") return <div className="overflow-hidden rounded-[1.75rem] border border-white/10 bg-[#10121f] p-4 shadow-[0_28px_90px_rgba(0,0,0,.42)]"><div className="grid grid-cols-[1.2fr_repeat(3,.8fr)] gap-px overflow-hidden rounded-xl bg-white/10 text-xs"><span className="bg-[#0c0e1a] p-3 text-white/40">Capability</span>{["MP4", "MOV", "WebM"].map((format) => <span key={format} className="bg-[#0c0e1a] p-3 text-center font-semibold text-white">{format}</span>)}{[["Upload", true, true, true], ["Metadata probe", true, true, true], ["Recommended", true, false, false], ["MP4 output", true, true, true]].flatMap((row) => row.map((cell, index) => <span key={`${row[0]}-${index}`} className={`bg-[#10121f] p-3 ${index === 0 ? "text-white/55" : "text-center"}`}>{typeof cell === "boolean" ? cell ? <Check size={14} className="mx-auto text-emerald-200" /> : <X size={14} className="mx-auto text-white/20" /> : cell}</span>))}</div><p className="mt-4 flex items-center gap-2 text-[10px] text-white/40"><FileVideo2 size={13} className="text-cyan-100" /> Container support still depends on readable codecs and valid media metadata.</p></div>;
  if (page.kind === "faq") return <div className="rounded-[1.75rem] border border-white/10 bg-[#10121f] p-4 shadow-[0_28px_90px_rgba(0,0,0,.42)]"><p className="text-xs font-semibold uppercase tracking-[.16em] text-cyan-100">Most asked</p>{["Can I edit the mask?", "What if a job fails?", "Can it remove any watermark?"].map((question, index) => <div key={question} className="mt-3 flex items-center gap-3 rounded-xl border border-white/10 bg-white/[.025] p-4"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#4f7cff]/15 text-xs font-bold text-cyan-100">{index + 1}</span><span className="text-sm font-medium text-white/75">{question}</span><ArrowRight size={14} className="ml-auto text-white/25" /></div>)}</div>;
  if (page.kind === "changelog") return <div className="rounded-[1.75rem] border border-white/10 bg-[#10121f] p-6 shadow-[0_28px_90px_rgba(0,0,0,.42)]"><div className="relative border-l border-white/10 pl-7">{[["Marketing", "Complete public pages"], ["Editor", "Mask and preview controls"], ["Operations", "Plans, credits, and retention"]].map(([area, update], index) => <div key={area} className="relative pb-7 last:pb-0"><span className="absolute -left-[33px] top-0 h-3 w-3 rounded-full border-2 border-[#10121f] bg-cyan-300" /><p className="text-[10px] font-semibold uppercase tracking-wider text-cyan-100">July 2026 · {area}</p><p className="mt-1 text-sm font-medium text-white">{update}</p><span className="mt-2 inline-flex rounded-full bg-emerald-300/10 px-2 py-1 text-[9px] text-emerald-200">Shipped</span></div>)}</div></div>;
  if (page.kind === "about") return <div className="grid gap-3 sm:grid-cols-2"><div className="sm:col-span-2 rounded-[1.5rem] border border-cyan-300/20 bg-[radial-gradient(circle_at_top_right,rgba(34,211,238,.14),transparent_55%)] p-6"><Sparkles className="text-cyan-100" /><p className="mt-5 text-2xl font-semibold tracking-[-.03em]">Review first.</p><p className="mt-2 max-w-md text-sm leading-6 text-white/50">A useful suggestion should always lead to an understandable choice.</p></div>{[["Automation", "Find and process"], ["Control", "Select and approve"]].map(([title, copy]) => <div key={title} className="rounded-[1.5rem] border border-white/10 bg-[#10121f] p-5"><p className="text-xs font-semibold text-cyan-100">{title}</p><p className="mt-2 text-sm text-white/50">{copy}</p></div>)}</div>;
  if (page.kind === "status") return <div className="rounded-[1.75rem] border border-white/10 bg-[#10121f] p-5 shadow-[0_28px_90px_rgba(0,0,0,.42)]"><div className="grid grid-cols-2 gap-3">{[["Web", "Interface"], ["API", "Accounts"], ["Storage", "Media"], ["Workers", "Processing"]].map(([title, copy]) => <div key={title} className="rounded-xl border border-white/10 bg-white/[.025] p-4"><span className="h-2 w-2 rounded-full bg-cyan-300 block" /><p className="mt-3 text-sm font-medium text-white">{title}</p><p className="mt-1 text-[10px] text-white/40">{copy}</p></div>)}</div><p className="mt-4 text-[10px] leading-5 text-white/40">Live operational state is verified through authenticated health and administration tools.</p></div>;
  return <div className="rounded-[1.75rem] border border-white/10 bg-[#10121f] p-6 shadow-[0_28px_90px_rgba(0,0,0,.42)]"><div className="flex items-center justify-between border-b border-white/10 pb-4"><span className="text-xs font-semibold text-white">{page.title}</span><span className="rounded-full border border-white/10 px-2 py-1 text-[9px] text-white/40">{page.lastUpdated}</span></div><div className="mt-5 space-y-3">{page.sections.slice(0, 4).map((section, index) => <div key={section.id} className="flex gap-3"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-lg bg-[#4f7cff]/15 text-[10px] font-bold text-cyan-100">{index + 1}</span><span className="text-sm text-white/55">{section.title}</span></div>)}</div></div>;
}

function EntryCard({ entry, index, dark = false }: { entry: SeoEntry; index: number; dark?: boolean }) {
  return <article className={`rounded-2xl border p-6 ${dark ? "border-white/10 bg-[#10121f]" : "border-slate-200 bg-white shadow-[0_12px_30px_rgba(21,24,31,.05)]"}`}><div className="flex items-start justify-between gap-3"><span className={`grid h-9 w-9 place-items-center rounded-xl text-xs font-bold ${dark ? "bg-cyan-300/10 text-cyan-100" : "bg-[#4f7cff]/10 text-[#4f7cff]"}`}>{String(index + 1).padStart(2, "0")}</span>{entry.status && <span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${entry.status === "Planned" ? "bg-amber-300/10 text-amber-700" : "bg-emerald-300/15 text-emerald-700"}`}>{entry.status}</span>}</div><h3 className="mt-5 text-lg font-semibold">{entry.title}</h3><p className={`mt-2 text-sm leading-6 ${dark ? "text-white/50" : "text-slate-600"}`}>{entry.body}</p>{entry.bullets && <ul className="mt-4 space-y-2">{entry.bullets.map((bullet) => <li key={bullet} className="flex gap-2 text-sm"><Check size={14} className="mt-1 shrink-0 text-cyan-500" />{bullet}</li>)}</ul>}</article>;
}

function StoryLayout({ page }: { page: SeoPage }) {
  return <>{page.sections.map((section, sectionIndex) => <section id={section.id} key={section.id} className={`scroll-mt-24 py-20 sm:py-28 ${sectionIndex % 2 === 0 ? "bg-[#f5f6f8] text-[#0c0e1a]" : "bg-[#0c0e1a] text-white"}`}><div className="mx-auto grid max-w-7xl gap-8 px-5 sm:px-8 lg:grid-cols-[.72fr_1.28fr] lg:gap-16 lg:px-10"><div><p className={`text-xs font-semibold uppercase tracking-[.18em] ${sectionIndex % 2 === 0 ? "text-[#4f7cff]" : "text-cyan-100"}`}>{String(sectionIndex + 1).padStart(2, "0")}</p><h2 className="mt-4 text-3xl font-semibold tracking-[-.04em] sm:text-4xl">{section.title}</h2>{section.body && <p className={`mt-5 leading-7 ${sectionIndex % 2 === 0 ? "text-slate-600" : "text-white/55"}`}>{section.body}</p>}</div><div>{section.entries && <div className="grid gap-4 sm:grid-cols-2">{section.entries.map((entry, index) => <EntryCard key={entry.title} entry={entry} index={index} dark={sectionIndex % 2 !== 0} />)}</div>}{section.bullets && <ul className={`overflow-hidden rounded-3xl border ${sectionIndex % 2 === 0 ? "border-slate-200 bg-white" : "border-white/10 bg-[#10121f]"}`}>{section.bullets.map((bullet, index) => <li key={bullet} className={`flex gap-4 border-b p-5 last:border-0 ${sectionIndex % 2 === 0 ? "border-slate-100 text-slate-700" : "border-white/10 text-white/60"}`}><span className={`grid h-7 w-7 shrink-0 place-items-center rounded-full text-xs font-bold ${sectionIndex % 2 === 0 ? "bg-[#4f7cff]/10 text-[#4f7cff]" : "bg-cyan-300/10 text-cyan-100"}`}>{index + 1}</span><span className="pt-0.5 text-sm leading-6">{bullet}</span></li>)}</ul>}</div></div></section>)}</>;
}

function WorkflowLayout({ page }: { page: SeoPage }) {
  let count = 0;
  return <section className="bg-[#f5f6f8] py-24 text-[#0c0e1a] sm:py-32"><div className="mx-auto max-w-6xl px-5 sm:px-8">{page.sections.map((section) => <div id={section.id} key={section.id} className="scroll-mt-24 grid gap-6 border-b border-slate-200 py-10 first:pt-0 last:border-0 lg:grid-cols-[240px_1fr]"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#4f7cff]">{section.title}</p></div><ol className="grid gap-4 sm:grid-cols-2">{section.entries?.map((entry) => { count += 1; return <li key={entry.title} className="relative rounded-2xl border border-slate-200 bg-white p-6 shadow-[0_12px_30px_rgba(21,24,31,.05)]"><span className="text-xs font-bold text-[#4f7cff]">STEP {String(count).padStart(2, "0")}</span><h2 className="mt-4 text-xl font-semibold">{entry.title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{entry.body}</p></li>; })}</ol></div>)}</div></section>;
}

function FAQLayout({ page }: { page: SeoPage }) {
  return <section className="bg-[#f5f6f8] py-24 text-[#0c0e1a] sm:py-32"><div className="mx-auto max-w-5xl px-5 sm:px-8">{page.sections.map((section) => <section id={section.id} key={section.id} className="scroll-mt-24 border-b border-slate-200 py-9 first:pt-0 last:border-0"><h2 className="text-2xl font-semibold tracking-[-.03em]">{section.title}</h2><div className="mt-5 space-y-3">{section.entries?.map((entry) => <details key={entry.title} className="group rounded-2xl border border-slate-200 bg-white shadow-[0_8px_24px_rgba(21,24,31,.04)]"><summary className="flex min-h-16 cursor-pointer list-none items-center justify-between gap-4 px-5 font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-[#4f7cff]"><span>{entry.title}</span><ChevronDown size={18} className="shrink-0 text-slate-400 transition-transform group-open:rotate-180" /></summary><div className="faq-answer"><div><p className="px-5 pb-6 pr-12 leading-7 text-slate-600">{entry.body}</p></div></div></details>)}</div></section>)}</div></section>;
}

function LegalLayout({ page }: { page: SeoPage }) {
  return <section className="bg-[#f5f6f8] py-16 text-[#0c0e1a] sm:py-24"><div className="mx-auto grid max-w-7xl gap-10 px-5 sm:px-8 lg:grid-cols-[260px_minmax(0,760px)] lg:justify-center lg:px-10"><aside className="lg:sticky lg:top-24 lg:self-start"><p className="text-xs font-semibold uppercase tracking-[.16em] text-slate-400">On this page</p><nav aria-label="Table of contents" className="mt-4 space-y-1">{page.sections.map((section) => <a key={section.id} href={`#${section.id}`} className="block rounded-lg px-3 py-2 text-sm text-slate-600 hover:bg-white hover:text-[#4f7cff] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#4f7cff]">{section.title}</a>)}</nav><p className="mt-6 flex items-center gap-2 text-xs text-slate-400"><Clock3 size={13} /> Last updated {page.lastUpdated}</p></aside><article className="rounded-3xl border border-slate-200 bg-white px-6 py-3 shadow-[0_18px_50px_rgba(21,24,31,.06)] sm:px-10">{page.sections.map((section) => <section id={section.id} key={section.id} className="scroll-mt-28 border-b border-slate-100 py-8 last:border-0"><h2 className="text-2xl font-semibold tracking-[-.025em]">{section.title}</h2>{section.body && <p className="mt-4 leading-8 text-slate-600">{section.body}</p>}{section.bullets && <ul className="mt-5 space-y-3">{section.bullets.map((bullet) => <li key={bullet} className="flex gap-3 text-slate-600"><Check size={16} className="mt-1 shrink-0 text-[#4f7cff]" />{bullet}</li>)}</ul>}</section>)}</article></div></section>;
}

function FormatsLayout({ page }: { page: SeoPage }) {
  return <section className="bg-[#f5f6f8] py-24 text-[#0c0e1a] sm:py-32"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className="overflow-x-auto rounded-3xl border border-slate-200 bg-white shadow-[0_16px_44px_rgba(21,24,31,.06)]"><table className="w-full min-w-[720px] text-left text-sm"><caption className="sr-only">ClearFrame format compatibility</caption><thead><tr className="border-b border-slate-200"><th className="px-5 py-4 text-xs uppercase tracking-wider text-slate-400">Container</th><th className="px-5 py-4">Upload</th><th className="px-5 py-4">Recommended source</th><th className="px-5 py-4">Output handling</th></tr></thead><tbody>{[["MP4", "Supported", "H.264 + AAC", "MP4 · H.264 · AAC"], ["MOV", "Supported", "Readable video + audio streams", "MP4 · H.264 · AAC"], ["WebM", "Supported", "Readable VPx/AV streams", "Audio may transcode to AAC"]].map((row) => <tr key={row[0]} className="border-b border-slate-100 last:border-0">{row.map((cell, index) => <td key={cell} className={`px-5 py-4 ${index === 0 ? "font-semibold" : "text-slate-600"}`}>{index === 1 && <Check size={14} className="mr-2 inline text-emerald-500" />}{cell}</td>)}</tr>)}</tbody></table></div><div className="mt-12"><StoryLayout page={{ ...page, sections: page.sections }} /></div></div></section>;
}

function ComplianceLayout({ page }: { page: SeoPage }) {
  const allowed = page.sections.find((section) => section.id === "allowed");
  const denied = page.sections.find((section) => section.id === "not-allowed");
  const rest = page.sections.filter((section) => !["allowed", "not-allowed"].includes(section.id));
  const list = (section: SeoSection | undefined, positive: boolean) => <div className={`rounded-3xl border p-7 ${positive ? "border-emerald-300/25 bg-emerald-300/[.06]" : "border-rose-300/25 bg-rose-300/[.05]"}`}><div className={`flex items-center gap-2 ${positive ? "text-emerald-200" : "text-rose-200"}`}>{positive ? <CircleCheck /> : <CircleAlert />}<h2 className="text-xl font-semibold text-white">{section?.title}</h2></div><ul className="mt-6 space-y-3">{section?.bullets?.map((bullet) => <li key={bullet} className="flex gap-3 text-sm text-white/60">{positive ? <Check size={16} className="mt-0.5 shrink-0 text-emerald-200" /> : <X size={16} className="mt-0.5 shrink-0 text-rose-200" />}{bullet}</li>)}</ul></div>;
  return <><section className="bg-[#0c0e1a] py-24 sm:py-32"><div className="mx-auto grid max-w-6xl gap-5 px-5 sm:grid-cols-2 sm:px-8">{list(allowed, true)}{list(denied, false)}</div></section><StoryLayout page={{ ...page, sections: rest }} /></>;
}

function ChangelogLayout({ page }: { page: SeoPage }) {
  return <section className="bg-[#f5f6f8] py-24 text-[#0c0e1a] sm:py-32"><div className="mx-auto max-w-4xl px-5 sm:px-8"><div className="relative border-l border-slate-200 pl-8">{page.sections.map((section) => <section id={section.id} key={section.id} className="relative scroll-mt-24 pb-12 last:pb-0"><span className="absolute -left-[39px] top-0 h-5 w-5 rounded-full border-4 border-[#f5f6f8] bg-[#4f7cff]" /><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#4f7cff]">{section.title}</p><div className="mt-5 space-y-4">{section.entries?.map((entry) => <article key={entry.title} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-[0_12px_30px_rgba(21,24,31,.05)]"><div className="flex flex-wrap items-start justify-between gap-3"><h2 className="text-xl font-semibold">{entry.title}</h2><span className="rounded-full bg-emerald-100 px-2.5 py-1 text-[10px] font-semibold text-emerald-700">{entry.status}</span></div><p className="mt-3 leading-7 text-slate-600">{entry.body}</p></article>)}</div></section>)}</div></div></section>;
}

function CTA({ page }: { page: SeoPage }) {
  return <section className="bg-[#07080f] px-5 py-20 sm:px-8 sm:py-24"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 rounded-[2rem] border border-cyan-300/20 bg-[radial-gradient(circle_at_top_right,rgba(34,211,238,.14),transparent_50%)] p-8 sm:flex-row sm:items-center sm:p-12"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-cyan-100">Next step</p><h2 className="mt-4 max-w-2xl text-3xl font-semibold tracking-[-.04em] text-white sm:text-4xl">{page.cta.title}</h2><p className="mt-3 max-w-2xl leading-7 text-white/55">{page.cta.body}</p></div><Link href={page.cta.href} className="inline-flex min-h-12 shrink-0 items-center justify-center gap-2 rounded-full bg-white px-6 font-semibold text-[#07080f] transition hover:bg-cyan-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300">{page.cta.label} <ArrowRight size={16} /></Link></div></section>;
}

export function SeoPageView({ page }: { page: SeoPage }) {
  return <article><header className="relative overflow-hidden px-5 pb-24 pt-32 sm:px-8 sm:pt-40 lg:px-10"><div className="pointer-events-none absolute inset-x-0 top-0 h-[42rem] bg-[radial-gradient(ellipse_at_top,rgba(79,124,255,.2),transparent_65%)]" /><div className="relative mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[.86fr_1.14fr]"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-cyan-100">{page.eyebrow}</p><h1 className="mt-5 max-w-4xl text-5xl font-semibold leading-[.98] tracking-[-.055em] sm:text-6xl">{page.heading}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/65">{page.intro}</p>{page.lastUpdated && <p className="mt-6 inline-flex items-center gap-2 rounded-full border border-white/10 px-3 py-2 text-xs text-white/45"><Clock3 size={13} /> Last updated {page.lastUpdated}</p>}</div><HeroArtwork page={page} /></div></header>{page.kind === "legal" ? <LegalLayout page={page} /> : page.kind === "faq" ? <FAQLayout page={page} /> : page.kind === "workflow" ? <WorkflowLayout page={page} /> : page.kind === "formats" ? <FormatsLayout page={page} /> : page.kind === "compliance" ? <ComplianceLayout page={page} /> : page.kind === "changelog" ? <ChangelogLayout page={page} /> : <StoryLayout page={page} />}<CTA page={page} /></article>;
}
