import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check, FileCheck2, Gauge, Layers3, ScanSearch, ShieldCheck, Upload, Workflow } from "lucide-react";

import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Pricing from "@/components/Pricing";
import { productFeatures } from "@/components/productConfig";
import { ArchitectureVisual, ProductHeroVisual } from "@/components/marketing/ProductVisuals";

export const metadata: Metadata = {
  title: "Product Overview — ClearFrame",
  description: "Explore ClearFrame's guided workflow for AI-assisted detection, precise masking, preview review, managed processing, and secure export.",
  alternates: { canonical: "/product" },
  openGraph: { title: "Everything you need to clean and review authorized footage — ClearFrame", description: "A guided, review-first video cleanup workflow.", url: "/product", type: "website", images: [{ url: "/demo/owned-after.png", width: 1200, height: 630, alt: "ClearFrame reviewed output" }] },
  twitter: { card: "summary_large_image", title: "ClearFrame Product Overview", description: "Detection, masking, preview, processing, and export in one guided workflow.", images: ["/demo/owned-after.png"] },
};

const workflow = [
  ["Upload", "Send an MP4, MOV, or WebM through a controlled upload path."],
  ["Analyze", "Read duration, dimensions, frame rate, codecs, and file integrity."],
  ["Detect", "Surface persistent overlays as candidates for review."],
  ["Mask", "Accept a candidate or draw the exact region yourself."],
  ["Track", "Use a static mask or review supported motion-aware propagation."],
  ["Preview", "Render a short result and compare it with the original."],
  ["Process", "Approve the credit estimate and monitor the queued job."],
  ["Export", "Download the H.264/AAC result through a temporary signed link."],
] as const;

const interfaceViews = [
  { title: "Project dashboard", copy: "See project status, media details, and the next available action.", icon: Gauge, accent: "from-[#4f7cff]/25" },
  { title: "Detection review", copy: "Compare ranked candidates and accept, reject, or retry.", icon: ScanSearch, accent: "from-cyan-300/20" },
  { title: "Mask workspace", copy: "Draw on the frame, tune the edge, and inspect the timeline.", icon: Layers3, accent: "from-violet-400/20" },
  { title: "Processing status", copy: "Follow queued, processing, encoding, and completed states.", icon: Workflow, accent: "from-amber-300/20" },
  { title: "Result page", copy: "Review output details and use the controlled download link.", icon: FileCheck2, accent: "from-emerald-300/20" },
] as const;

export default function ProductPage() {
  return <main className="min-h-screen overflow-hidden bg-[#07080f] text-[#f5f6fa]">
    <Navbar />
    <header className="relative px-5 pb-24 pt-32 sm:px-8 sm:pt-40 lg:px-10">
      <div className="pointer-events-none absolute inset-x-0 top-0 h-[46rem] bg-[radial-gradient(ellipse_at_top,rgba(79,124,255,.22),transparent_65%)]" />
      <div className="relative mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[.82fr_1.18fr]">
        <div><p className="inline-flex rounded-full border border-[#4f7cff]/35 bg-[#4f7cff]/10 px-3 py-1.5 text-xs font-semibold uppercase tracking-[.16em] text-[#b7c7ff]">The ClearFrame product</p><h1 className="mt-7 max-w-2xl text-5xl font-semibold leading-[.97] tracking-[-.055em] sm:text-6xl">Everything you need to clean and review <span className="bg-gradient-to-r from-[#7da1ff] to-[#67e8f9] bg-clip-text text-transparent">authorized footage.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/68">ClearFrame combines AI-assisted detection, manual mask control, preview-first processing, and managed video rendering in one guided workflow.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/signup" className="inline-flex min-h-12 items-center justify-center rounded-full bg-gradient-to-r from-[#4f7cff] via-[#6d5ef7] to-[#8b5cf6] px-6 font-semibold text-white shadow-[0_12px_32px_rgba(79,124,255,.28)] transition hover:brightness-110 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300">Create a free account</Link><a href="#workflow" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full border border-white/15 px-6 font-semibold text-white transition hover:bg-white/[.06] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300">See the workflow <ArrowRight size={16} /></a></div><div className="mt-7 flex flex-wrap gap-2 text-xs text-white/55"><span className="rounded-full border border-white/10 px-3 py-2">No card for Free</span><span className="rounded-full border border-white/10 px-3 py-2">Preview before full render</span><span className="rounded-full border border-white/10 px-3 py-2">Authorized use only</span></div></div>
        <ProductHeroVisual kind="overview" />
      </div>
    </header>

    <section id="workflow" className="scroll-mt-20 bg-[#f5f6f8] py-24 text-[#0c0e1a] sm:py-32"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className="grid gap-8 lg:grid-cols-[.72fr_1.28fr] lg:gap-16"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#4f7cff]">Complete product workflow</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.045em] sm:text-5xl">One connected path from source to reviewed output.</h2><p className="mt-5 max-w-lg leading-7 text-slate-600">Each stage leaves a visible decision or status behind, so you can return to the mask, retry a failed step, or understand what the system is doing.</p></div><ol className="relative grid gap-px overflow-hidden rounded-3xl border border-slate-200 bg-slate-200 sm:grid-cols-2">{workflow.map(([title, copy], index) => <li key={title} className="relative bg-white p-6 sm:p-7"><span className="text-xs font-bold tabular-nums text-[#4f7cff]">{String(index + 1).padStart(2, "0")}</span><h3 className="mt-4 text-lg font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{copy}</p></li>)}</ol></div></div></section>

    <section className="bg-[#07080f] py-24 sm:py-32"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-cyan-100">Core capabilities</p><h2 className="mt-4 max-w-3xl text-4xl font-semibold tracking-[-.045em] sm:text-5xl">The useful automation and the manual controls live together.</h2></div><p className="max-w-md leading-7 text-white/55">Open a capability to see the real workflow, interface state, review expectations, and limitations.</p></div><div className="mt-12 grid gap-4 lg:grid-cols-2">{productFeatures.map((feature, index) => { const Icon = feature.icon; return <Link key={feature.slug} href={feature.href} className={`group relative overflow-hidden rounded-3xl border border-white/10 bg-[#10121f] p-7 transition hover:-translate-y-1 hover:border-cyan-300/30 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300 ${index === 0 ? "lg:row-span-2 lg:p-9" : ""}`}><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#4f7cff]/15 text-cyan-100"><Icon size={20} /></span><ArrowRight size={18} className="text-white/25 transition group-hover:translate-x-1 group-hover:text-cyan-100" /></div><p className="mt-7 text-xs font-semibold uppercase tracking-[.16em] text-cyan-100">{feature.eyebrow}</p><h3 className="mt-2 text-2xl font-semibold tracking-[-.03em]">{feature.shortTitle}</h3><p className="mt-3 max-w-xl leading-7 text-white/52">{feature.description}</p><div className="mt-6 flex flex-wrap gap-2">{feature.bullets.map((bullet) => <span key={bullet} className="rounded-full border border-white/10 px-3 py-1.5 text-xs text-white/50">{bullet}</span>)}</div></Link>; })}</div></div></section>

    <section className="bg-[#f5f6f8] py-24 text-[#0c0e1a] sm:py-32"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#4f7cff]">Product interface overview</p><h2 className="mt-4 max-w-3xl text-4xl font-semibold tracking-[-.045em] sm:text-5xl">Every screen answers a different review question.</h2><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-5">{interfaceViews.map(({ title, copy, icon: Icon, accent }, index) => <article key={title} className={`relative min-h-64 overflow-hidden rounded-3xl border border-slate-200 bg-gradient-to-br ${accent} to-white p-6 shadow-[0_14px_36px_rgba(21,24,31,.06)] lg:even:translate-y-8`}><span className="grid h-11 w-11 place-items-center rounded-xl border border-slate-200 bg-white text-[#4f7cff]"><Icon size={19} /></span><p className="mt-8 text-xs font-bold uppercase tracking-[.15em] text-slate-400">View {String(index + 1).padStart(2, "0")}</p><h3 className="mt-2 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{copy}</p></article>)}</div></div></section>

    <section className="bg-[#0c0e1a] py-24 sm:py-32"><div className="mx-auto grid max-w-7xl gap-12 px-5 sm:px-8 lg:grid-cols-2 lg:px-10"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-cyan-100">Human control</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.045em] sm:text-5xl">AI shortens the search. It does not approve the edit.</h2><p className="mt-5 max-w-xl leading-7 text-white/55">Detection can suggest a region and tracking can reduce repetitive work where supported. The user still chooses the mask, reviews the preview, approves the credit cost, and starts the full job.</p><div className="mt-8 space-y-3">{[["ClearFrame", "Samples frames, ranks candidates, queues processing, and reports status."], ["Editor", "Confirms authorization, refines the mask, reviews quality, and approves export."]].map(([role, copy]) => <div key={role} className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><p className="font-semibold text-white">{role}</p><p className="mt-2 text-sm leading-6 text-white/50">{copy}</p></div>)}</div></div><div className="rounded-[2rem] border border-cyan-300/20 bg-[radial-gradient(circle_at_top_right,rgba(34,211,238,.12),transparent_45%)] p-8"><div className="flex items-center gap-3 text-cyan-100"><ShieldCheck /><span className="text-xs font-semibold uppercase tracking-[.18em]">Authorization stays visible</span></div><h3 className="mt-6 text-3xl font-semibold tracking-[-.04em]">The product is for footage you own or are licensed to edit.</h3><ul className="mt-6 space-y-3 text-sm text-white/60">{["Ownership confirmation before upload", "No DRM or access-control removal", "No third-party ownership-mark removal", "Private storage paths and controlled downloads", "Configured cleanup and retention windows"].map((item) => <li key={item} className="flex gap-2"><Check size={16} className="mt-0.5 shrink-0 text-cyan-100" />{item}</li>)}</ul><Link href="/authorized-use" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-cyan-100 hover:text-white">Read the authorized-use guide <ArrowRight size={15} /></Link></div></div></section>

    <section className="bg-[#07080f] py-24 sm:py-32"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-cyan-100">Managed processing architecture</p><h2 className="mt-4 max-w-3xl text-4xl font-semibold tracking-[-.045em] sm:text-5xl">A simple view of what happens after approval.</h2></div><p className="max-w-md leading-7 text-white/55">The public diagram shows the hand-offs that matter without exposing credentials, storage paths, or worker internals.</p></div><div className="mt-12"><ArchitectureVisual /></div></div></section>

    <section className="bg-[#0c0e1a]"><div className="mx-auto max-w-7xl px-5 pt-24 sm:px-8 sm:pt-32 lg:px-10"><div className="mx-auto max-w-3xl text-center"><p className="text-xs font-semibold uppercase tracking-[.18em] text-cyan-100">Plans and capacity</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.045em] sm:text-5xl">Start with the same review workflow, then choose the capacity you need.</h2><p className="mt-5 leading-7 text-white/55">Prices and credit allowances are read from the Plan API. Limits that are not configured per plan remain platform-managed rather than being guessed here.</p></div></div><Pricing compact /></section>

    <section className="bg-[#07080f] px-5 py-20 sm:px-8 sm:py-24"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 rounded-[2rem] border border-cyan-300/20 bg-[radial-gradient(circle_at_top_right,rgba(34,211,238,.14),transparent_50%)] p-8 sm:flex-row sm:items-center sm:p-12"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-cyan-100">Begin with a reviewable project</p><h2 className="mt-4 max-w-2xl text-3xl font-semibold tracking-[-.04em] sm:text-4xl">Start your first project and keep every important decision visible.</h2></div><Link href="/signup" className="inline-flex min-h-12 shrink-0 items-center justify-center rounded-full bg-white px-6 font-semibold text-[#07080f] transition hover:bg-cyan-50">Start your first project</Link></div></section>
    <Footer />
  </main>;
}
